# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.CharField(choices=[('ASSIGNED', 'assigned'), ('IN_PROGRESS', 'in progress'), ('TESTED', 'tested'), ('FINISHED', 'finished')], default='ASSIGNED', max_length=50),
        ),
    ]
