# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 22:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171204_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mails', to=settings.AUTH_USER_MODEL),
        ),
    ]
